data:
  name: pl
  path: /home/worker/users/WYG/IFP-diffusion_v2/datasets/crossdocked_pocket10
  transform:
    ligand_atom_mode: add_aromatic
    random_rot: False

model:
  model_mean_type: C0  # ['noise', 'C0']
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 2.e-3
  v_beta_schedule: cosine
  v_beta_s: 0.01
  num_diffusion_timesteps: 1000
  loss_v_weight: 100.
  sample_time_method: symmetric  # ['importance', 'symmetric']
  ckpt_path : ''
  time_emb_dim: 0
  time_emb_mode: simple
  center_pos_mode: protein

  node_indicator: True
  model_type: uni_o2
  num_blocks: 1
  num_layers: 9
  hidden_dim: 128
  n_heads: 16
  edge_feat_dim: 5  # edge type feat [4 or 1 or 5]
  num_r_gaussian: 20
  knn: 32 # !
  num_node_types: 8
  act_fn: relu
  norm: True
  cutoff_mode: knn  # [radius, none]
  ew_net_type: global  # [r, m, none]
  num_x2h: 1
  num_h2x: 1
  r_max: 10.
  x2h_out_fc: False
  sync_twoup: False

  if_ifp: True # True
  if_catifp_basic: True # True
  hidden_ifp: True # True
  if_predict_loss : True # True

  # ---------add 250606---------
  out_add_refer_ligand: True
  hidden_refer_ligand: False
  # ---------add 250609---------
  alpha_refer: False

  # ---------add 250610---------
  virtual_refer_node: True

  # ---------add 250616---------
  refer_ligand_cat: True
  # ---------------------------
  refer_ligand_type: unimol # ['unimol', 'egnn', 'gnn']
  refer_ligand:
    k: 10
    num_layers: 2
    pool_type: mean
    num_r_gaussian: 0
    edge_feat_dim: 1

train:
  seed: 2021
  batch_size: 2 #6
  num_workers: 4
  n_acc_batch: 1
  max_iters: 600000 #60000 or 600000
  val_freq: 120000  #100 #2000 20000 40000
  pos_noise_std: 0.1
  max_grad_norm: 8.0
  bond_loss_weight: 1.0
  optimizer:
    type: adam
    lr: 5.e-4
    weight_decay: 0
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 10
    min_lr: 1.e-6
